import React, {useEffect,useState,useRef,useMemo,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const MathText=lazy(()=>import('./MathText.jsx'));
const units=['Atomic structure','Bonding & structure','Properties of matter','Chemical reactions','Kinetics','Thermodynamics','Equilibrium','Acids & bases','Energy & electrochemistry'];
const fmt=n=>Number(n).toPrecision(5).replace(/\.0+(?=e|$)/,'');
function Graph({visual}) {
 const [point,setPoint]=useState(0),[table,setTable]=useState(false);
 useEffect(()=>{setPoint(0);setTable(false)},[visual?.dataset_id]);
 const geometry=useMemo(()=>{
  if(!visual)return null;
  const p=visual.points,x0=p[0].x,x1=p.at(-1).x,ys=p.map(v=>v.y);let y0=Math.min(...ys),y1=Math.max(...ys);if(y0===y1){y0-=1;y1+=1}
  const pad=(y1-y0)*.06;y0-=pad;y1+=pad;
  const X=x=>68+(x-x0)/(x1-x0)*342,Y=y=>235-(y-y0)/(y1-y0)*205;
  return {p,x0,x1,y0,y1,X,Y,path:p.map((v,i)=>`${i?'L':'M'}${X(v.x).toFixed(2)},${Y(v.y).toFixed(2)}`).join(' ')};
 },[visual]);
 if(!geometry)return <div className="graph-empty"><span className="orb">↗</span><h3>Make chemistry visible</h3><p>Choose a model, predict its shape, then inspect the relationship.</p></div>;
 const {p,X,Y,x0,x1,y0,y1,path}=geometry,selected=p[Math.min(point,p.length-1)];
 return <><h3>{visual.title}</h3><svg viewBox="0 0 440 300" role="img" aria-label={`${visual.title}. ${visual.x_label} versus ${visual.y_label}. Full data table below.`}>
 {[0,1,2,3,4].map(i=>{const x=x0+(x1-x0)*i/4,y=y0+(y1-y0)*i/4;return <g key={i}><line x1="68" x2="410" y1={Y(y)} y2={Y(y)} className="grid"/><text x="59" y={Y(y)+4} textAnchor="end">{fmt(y)}</text><text x={X(x)} y="254" textAnchor="middle">{fmt(x)}</text></g>})}
 <path d="M68 30 V235 H410" className="axis"/><path d={path} className="curve"/><circle cx={X(selected.x)} cy={Y(selected.y)} r="5" className="dot"/>
 <text x="239" y="283" textAnchor="middle">{visual.x_label}</text><text transform="translate(14 135) rotate(-90)" textAnchor="middle">{visual.y_label}</text></svg>
 <label className="slider-label" htmlFor="coordinate">Inspect a point <span>{point+1} / {p.length}</span></label><input id="coordinate" type="range" min="0" max={p.length-1} value={point} onChange={e=>setPoint(+e.target.value)}/>
 <output className="coordinates" aria-live="polite">x = {fmt(selected.x)} · y = {fmt(selected.y)}</output>
 <p className="micro">Original model-generated data. {visual.assumptions}</p>
 <button className="text-button" onClick={()=>setTable(!table)} aria-expanded={table}>{table?'Hide':'Show'} accessible data table</button>
 {table&&<div className="table-scroll" tabIndex="0"><table><caption>{visual.title}</caption><thead><tr><th>{visual.x_label}</th><th>{visual.y_label}</th></tr></thead><tbody>{p.map((r,i)=><tr key={i}><td>{r.x.toPrecision(12)}</td><td>{r.y.toPrecision(12)}</td></tr>)}</tbody></table></div>}</>;
}
function App(){
 const [catalog,setCatalog]=useState(null),[token,setToken]=useState(''),[topic,setTopic]=useState('3.4'),[family,setFamily]=useState('ideal_gas'),[question,setQuestion]=useState(null);
 const [messages,setMessages]=useState([]),[text,setText]=useState(''),[unit,setUnit]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [visual,setVisual]=useState(null),[graphFamily,setGraphFamily]=useState('gas_pv'),[variant,setVariant]=useState(1),[tab,setTab]=useState('graph'),[expression,setExpression]=useState(''),[claimed,setClaimed]=useState(''),[attempt,setAttempt]=useState(''),[equation,setEquation]=useState('');
 const [evidence,setEvidence]=useState(null),[showEvidence,setShowEvidence]=useState(false);const bottom=useRef(null);
 useEffect(()=>{Promise.all([fetch('/api/catalog').then(r=>r.json()),fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json())]).then(([c,s])=>{if(s.error)throw Error(s.error);setCatalog(c);setToken(s.token)}).catch(e=>setError('Could not connect to the local server. '+e.message))},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages]);
 const families=catalog?.families.filter(f=>f.topic_id===topic)||[];
 const sims=catalog?.simulations.filter(s=>s.topic_ids.includes(topic))||[];
 function chooseTopic(id){setTopic(id);setFamily(catalog.families.find(f=>f.topic_id===id&&!f.id.startsWith('concept'))?.id||`concept-${id}`)}
 async function api(route,data={}){const r=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.error||'Request failed');return out}
 async function action(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function append(role,message,extra={}){setMessages(m=>[...m,{role,message,...extra}])}
 async function practice(){await action(async()=>{const r=await api('practice',{topic,family});setQuestion(r.question);setUnit(r.question.answer_unit||'');setVisual(r.question.visual);setMessages([{role:'tutor',message:r.question.prompt}]);setText('');setAttempt('');setTab('graph')})}
 async function send(e){e.preventDefault();if(!text.trim())return;const input=text;await action(async()=>{const r=await api('chat',{text:input});append('you',input);append('tutor',r.message,{sources:r.sources,status:r.status});if(r.visuals?.length)setVisual(r.visuals[0]);setText('')})}
 async function end(){await action(async()=>{await api('end');setQuestion(null);setVisual(null);setMessages([]);setUnit('')})}
 async function inspectGraph(){await action(async()=>{const r=await api('graph',{family:graphFamily,variant});setVisual(r.visual)})}
 async function audit(){await action(async()=>{const r=await fetch('/api/evidence');setEvidence(await r.json());setShowEvidence(true)})}
 if(!catalog)return <main className="loading"><h1>Chemistry Studio</h1><p role="status">{error||'Opening your workspace…'}</p></main>;
 return <><header><a href="/" className="brand">CHEMISTRY STUDIO</a><span className="tagline">Understand the why.</span><span className="status"><i/>Practice ready</span><button className="text-button" onClick={audit} disabled={busy}>Coverage & proof</button></header>
 <div className="layout"><aside className="sidebar"><p className="eyebrow">YOUR COURSE</p><h2>AP Chemistry</h2><nav aria-label="Chemistry units">{units.map((u,i)=><button key={u} className={topic.startsWith(`${i+1}.`)?'unit active':'unit'} onClick={()=>chooseTopic(catalog.topics.find(t=>t.unit_id===i+1).id)}><span>{i+1}</span>{u}</button>)}</nav><div className="sidebar-note"><b>One step at a time.</b><p>Make a prediction. Try a method. Refine your reasoning.</p><span>9 units · 91 topics</span></div></aside>
 <main className="chat card"><div className="chat-head"><p className="eyebrow">GUIDED LEARNING</p><h1>Think it through.</h1><p>Build understanding, one useful question at a time.</p></div>
 <div className="practice-picker"><label>Topic<select value={topic} onChange={e=>chooseTopic(e.target.value)}>{catalog.topics.map(t=><option key={t.id} value={t.id}>{t.id} · {t.label}</option>)}</select></label><label>Practice family<select value={family} onChange={e=>setFamily(e.target.value)}>{families.map(f=><option key={f.id} value={f.id}>{f.id.replaceAll('_',' ')} · {f.variants} cases</option>)}</select></label><button disabled={busy} onClick={practice}>New practice</button></div>
 {question&&<div className="question-strip"><span>Practicing · {question.id}</span><button className="text-button" onClick={end} disabled={busy}>End practice</button></div>}
 <section className="conversation" aria-label="Conversation" aria-live="polite">{messages.length===0?<div className="welcome"><span className="orb">C<span>H</span></span><h2>What are you working on?</h2><p>Bring a question, choose a practice problem, or explore a graph. Start with what you know—even an unfinished idea helps.</p><div className="suggestions">{['How do I choose an equilibrium expression?','Help me interpret a titration curve.','Why does atomic radius change across a period?'].map(s=><button key={s} onClick={()=>setText(s)}>{s} <span>↗</span></button>)}</div></div>:messages.map((m,i)=><article key={i} className={'message '+m.role}><span className="eyebrow">{m.role==='you'?'YOU':'CHEMISTRY STUDIO'}</span><Suspense fallback={<div className="message-text">{m.message}</div>}><MathText text={m.message}/></Suspense>{m.status==='model_response'&&<small>AI guidance · reasoning is not independently verified</small>}{m.sources?.length>0&&<div className="sources">{m.sources.map(s=><a key={s.topic_id} href={s.source_url} target="_blank" rel="noreferrer">Topic {s.topic_id} ↗</a>)}</div>}</article>)}<div ref={bottom}/></section>
 {error&&<div className="error" role="alert">{error}</div>}{busy&&<p className="working" role="status">Working…</p>}
 {question&&<div className="attempt"><label>Your {question.answer_kind==='numeric'?'numerical answer':'explanation'}<input aria-label="Practice attempt" value={attempt} onChange={e=>setAttempt(e.target.value)} placeholder={question.answer_kind==='numeric'?'e.g. 2.5e-3':'State your reasoning'}/></label>{question.answer_kind==='numeric'&&<label>Unit<input aria-label="Answer unit" value={unit} onChange={e=>setUnit(e.target.value)}/></label>}<button disabled={busy||!attempt.trim()} onClick={()=>action(async()=>{const r=await api('attempt',{text:attempt,unit});append('you',attempt+' '+unit);append('tutor',r.message);setAttempt('')})}>Check attempt</button><button className="secondary" disabled={busy} onClick={()=>action(async()=>{const r=await api('hint');append('tutor',r.message)})}>Get a hint</button></div>}
 <form className="composer" onSubmit={send}><label className="sr-only" htmlFor="chat-input">Chemistry question or follow-up</label><textarea id="chat-input" maxLength="6000" value={text} onChange={e=>setText(e.target.value)} placeholder="Ask a chemistry question, or describe where you got stuck…" rows="3"/><div><span className="micro">{catalog.model_configured?'Text chat connected · AI can make mistakes':'Open-ended chat awaits server model configuration'}</span><button type="submit" disabled={busy||!text.trim()}>Send ↗</button></div></form></main>
 <aside className="right"><section className="card lab"><div className="tabs" role="group" aria-label="Learning tools">{['graph','steps','simulations'].map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='graph'?'Graph lab':t==='steps'?'Step checker':'PhET'}</button>)}</div>
 {tab==='graph'?<><h2>Explore the relationship</h2>{!question&&<><label>Model<select value={graphFamily} onChange={e=>setGraphFamily(e.target.value)}>{catalog.graphs.map(g=><option key={g.family_id} value={g.family_id}>{g.title}</option>)}</select></label><div className="model-controls"><label>Parameter set<input type="number" min="1" max="100" value={variant} onChange={e=>setVariant(+e.target.value)}/></label><button className="secondary" disabled={busy} onClick={inspectGraph}>Explore</button></div></>}<Graph visual={visual}/>{question&&!visual&&<p className="micro">Exploration is paused during this practice item to keep its answer hidden.</p>}</>:tab==='steps'?<><h2>Check your arithmetic</h2><p>Enter a calculation you have already set up. The checker gives feedback without displaying its result.</p><label>Expression<input value={expression} onChange={e=>setExpression(e.target.value)} placeholder="0.2 * 0.08206 * 298 / 5"/></label><label>Your result<input value={claimed} onChange={e=>setClaimed(e.target.value)} placeholder="Your calculated number"/></label><button disabled={busy||!expression||!claimed} onClick={()=>action(async()=>{const r=await api('step',{expression,claimed:Number(claimed)});append('tutor',r.message)})}>Check step</button><p className="micro">Supports + − * / ** sqrt(), ln(), log10(), exp(), abs(). Checks arithmetic only; it cannot validate your chemical setup or units.</p><h3>Check a reaction</h3><label>Your balanced equation<input value={equation} onChange={e=>setEquation(e.target.value)} placeholder="2 H2 + O2 -> 2 H2O"/></label><button disabled={busy||!equation.trim()} onClick={()=>action(async()=>{const r=await api('balance',{equation});append('tutor',r.message)})}>Check conservation</button><p className="micro">Separate species with spaces around +. Write ion charges as Fe^3+ or Cl^-. Checks atoms and charge, not whether a reaction occurs.</p></>:<><h2>Explore with PhET</h2><p>Simulation references matched to topic {topic}.</p>{(sims.length?sims:catalog.simulations).map(s=><a className="sim" key={s.id} href={s.repository_url} target="_blank" rel="noreferrer"><b>{s.title} ↗</b><span>{s.teaching_use}</span></a>)}<p className="micro">Official PhET project links. Simulations open externally; this tutor cannot observe or control them.</p></>}
 </section><section className="card note"><p className="eyebrow">LEARN WITH EVIDENCE</p><h2>Reasoning matters.</h2><p>Numerical checks help with a result. Your explanation shows why it makes sense.</p><button className="text-button" onClick={audit} disabled={busy}>See exactly what is tested ↗</button></section></aside></div>
 {showEvidence&&<div className="modal-backdrop" onKeyDown={e=>{if(e.key==='Escape')setShowEvidence(false);if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector('button').focus()}}}><section role="dialog" aria-modal="true" aria-label="Coverage and proof" className="modal"><button autoFocus className="close" onClick={()=>setShowEvidence(false)}>Close ×</button><h2>Coverage & proof</h2><p>Counts are generated from the database. Numerical variations are not distinct reasoning types.</p><pre>{JSON.stringify(evidence?.summary||evidence,null,2)}</pre><p>No finite test suite proves coverage of every possible AP Chemistry question. See the repository evidence for every family and topic, including unmet targets.</p></section></div>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
